---

  - name: Print loop var
    debug: msg={{account.account_id}}

  - name: Initialize vars
    set_fact:
      accountRelationshipsInfo_enriched: []

  - name: call Get sync relationships
    uri:
      url: "https://cloudsync.netapp.com/api/relationships-v2"
      method: GET
      headers:
        Authorization: "Bearer {{ token }}"
        x-account-id: "{{ account.account_id }}"
      status_code: 200,204,202
      timeout: 59
    register: get_relationships_response

  - name: Extract sync relationships for account {{ account.account_id }}
    set_fact:
      relationships: "{{ get_relationships_response.json }}"
  
  - name: "extract Sync relationshipd=d metadata"
    set_fact:
      accountRelationshipsInfo: '{{ relationships | json_query("[].{  relationship_id: relationshipId ,broker_id: dataBroker, phase: phase}") }}'

  - name: "enrich Accounts sync relationships with account id"
    set_fact:
      accountRelationshipsInfo_enriched: '{{ accountRelationshipsInfo_enriched + [item | combine({"Account_id": account.account_id, "Account_name": account.account_name})] }}'
    with_items: "{{ accountRelationshipsInfo }}"

  # - name: Print relationships for account {{ account.account_id }}
  #   debug: msg={{accountRelationshipsInfo_enriched}}
  
  - name: Combine relationships to one list
    set_fact:
      all_relationships: "{{ all_relationships + accountRelationshipsInfo_enriched }}"