---


  - name: call Get account agents API
    uri:
      url: "https://cloudmanager.cloud.netapp.com/agents-mgmt/agent?account_id={{ account_metadata.account_id }}"
      method: GET
      headers:
        Authorization: "Bearer {{ token }}"
        X-User-Token: "Bearer {{ token }}"
      status_code: 200,204,202
      timeout: 59
    register: account_agent_response

  - name: parse account agents API response
    set_fact:
      account_ids: '{{ account_agent_response.json | json_query("agents[].{ agent_id: agentId, agent_name: name, agent_status: status }")  }}'

#  - debug: var="account_ids"

  - name: accumalate to all_agents variable
    set_fact:
      all_agents: "{{ all_agents + [ { 'account_id' : account_metadata.account_id, 'agent_id' : item.agent_id, 'agent_name' : item.agent_name, 'agent_status' : item.agent_status } ] }}"
    with_items: "{{ account_ids }}"
