---

  - name: Print loop var
    debug: msg={{account_id.account_id}}
  - name: call Get sync relationships
    uri:
      url: "https://cloudsync.netapp.com/api/relationships-v2"
      method: GET
      headers:
        Authorization: "Bearer {{ token }}"
        x-account-id: "{{ account_id.account_id }}"
      status_code: 200,204,202
      timeout: 59
    register: get_relationships_response

  - name: Extract sync relationships for account {{ account_id.account_id }}
    set_fact:
      relationships: "{{ get_relationships_response.json }}"
  
  - name: Print relationships for account {{ account_id.account_id }}
    debug: msg={{relationships}}
  
  - name: Combine relationships to one list
    set_fact:
      all_relationships: "{{ all_relationships + relationships }}"